spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/iykyk
    username: root
    password: password
  jpa:
    hibernate:
      ddlAuto: none
    showSql: true

---

app:
  mode: development
  security:
    jwt:
      token:
        secret-key: "secret" # Replace own secret key here